
package interfaceGraficaGislaine;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Visualiza extends javax.swing.JFrame {

    private Cadastro telaDeCadastro;
    
    //array para manter as pessoas "salvas"
    private ArrayList<Automovel> array;
    
    public Visualiza() {
        initComponents();
        
        telaDeCadastro =  new Cadastro(this);
        
        this.array = new ArrayList<Automovel>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAutomovel = new javax.swing.JTable();
        btVisualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaAutomovel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Marca", "Modelo", "Placa", "Cor", "Ano"
            }
        ));
        jScrollPane1.setViewportView(tabelaAutomovel);

        btVisualizar.setText("Visualizar");
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btExcluir)
                .addGap(18, 18, 18)
                .addComponent(btNovo)
                .addGap(33, 33, 33)
                .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btNovo)
                        .addComponent(btExcluir))
                    .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
    
        int linhaSelecionda = tabelaAutomovel.getSelectedRow();
                
        if (linhaSelecionda < 0){
            JOptionPane.showMessageDialog(this, "Selecione uma linha", "AVISO", JOptionPane.WARNING_MESSAGE);
        }else{
            this.telaDeCadastro.mostrarAutomovel(array.get(linhaSelecionda));
            this.setVisible(false);
        }
       
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
       this.telaDeCadastro.setVisible(true);
            
        //deixa esta tela invisível
        this.setVisible(false);
                              
    }//GEN-LAST:event_btNovoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int selectedIndex = tabelaAutomovel.getSelectedRow();
        
        if (selectedIndex < 0){
            //nenhuma linha selecionada
            JOptionPane.showMessageDialog(this, "Selecione um item qualquer","AVISO",JOptionPane.WARNING_MESSAGE);
        }else{
            //um item está selecionado, então remove
            this.removeAutomovel(selectedIndex);  
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    //insere Automovel à tabela
    public void addAutomovel(Automovel a){
        this.array.add(a);
        this.addAutomovelToTable(a);
    }
    
    
    public void addAutomovelToTable(Automovel a){
        DefaultTableModel model = (DefaultTableModel)tabelaAutomovel.getModel();
        model.addRow(new Object[]{a.getNome(), a.getMarca(), a.getModelo(), a.getPlaca(), a.getAno(), a.getCor()});
    } 
    //remove do array
    public void removeAutomovel(int i){
        array.remove(i);
        removeAutomovelFromTable(i);
    }
    
    
    //remove da tabela
    public void removeAutomovelFromTable(int i){
        DefaultTableModel model = (DefaultTableModel)tabelaAutomovel.getModel();
        model.removeRow(i);
    }
    public void redefineTabela(){
        DefaultTableModel model = (DefaultTableModel)tabelaAutomovel.getModel();
        while (model.getRowCount() > 0){
            model.removeRow(0);
        }
        
        for (Automovel a : array){
            model.addRow(new Object[]{a.getNome(), a.getMarca(), a.getModelo(), a.getPlaca(), a.getAno(), a.getCor()});
    } 
    }         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAutomovel;
    // End of variables declaration//GEN-END:variables

}

